name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Push Frontend
      run: |
        docker build -t shiv201/frontend:latest -f Dockerfile-frontend .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push shiv201/frontend:latest

    - name: Build and Push Backend
      run: |
        docker build -t shiv201/backend:latest -f Dockerfile-backend .
        docker push shiv201/backend:latest

    - name: Set up KUBECONFIG
      run: |
       echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
       export KUBECONFIG=$PWD/kubeconfig.yaml
       kubectl get nodes  # just to verify it's working

    - name: Apply Kubernetes Manifests
      run: |
       export KUBECONFIG=$PWD/kubeconfig.yaml
       kubectl apply -f k8s/

